imports:
  - { resource: ../common.yml }
  - { resource: installer.yml }
  - { resource: builder.yml }
  - { resource: installer.yml }
  - { resource: product_filter.yml }
  - { resource: product_sync.yml }
  - { resource: provider.yml }

services:
  PrestaShop\Module\PsxMarketingWithGoogle\Api\LocalGoogleApi:
    class: PrestaShop\Module\PsxMarketingWithGoogle\Api\LocalGoogleApi
    public: true
    arguments:
      - '@PrestaShop\Module\PsxMarketingWithGoogle\OAuth\GoogleCredentialRepository'
      - '@PrestaShop\Module\PsxMarketingWithGoogle\OAuth\GoogleConnectionService'
      - '@PrestaShop\Module\PsxMarketingWithGoogle\OAuth\GoogleOAuthRedirectUriResolver'
      - ~
      - ~
      - '@PrestaShop\Module\PsxMarketingWithGoogle\Merchant\MerchantAccountService'
      - '@PrestaShop\Module\PsxMarketingWithGoogle\ProductSync\SyncProcessor'
      - '@PrestaShop\Module\PsxMarketingWithGoogle\ProductSync\CatalogFilterSettingsInterface'
