enum ActionsTypes {
  WARMUP_STORE = 'WARMUP_STORE',
  SAVE_SELECTED_GOOGLE_MERCHANT_ACCOUNT = 'SAVE_SELECTED_GOOGLE_MERCHANT_ACCOUNT',
  REQUEST_ROUTE_TO_GOOGLE_AUTH = 'REQUEST_ROUTE_TO_GOOGLE_AUTH',
  REQUEST_GOOGLE_SETTINGS_STATUS = 'REQUEST_GOOGLE_SETTINGS_STATUS',
  REQUEST_GOOGLE_ACCOUNT_DETAILS = 'REQUEST_GOOGLE_ACCOUNT_DETAILS',
  REQUEST_GMC_LIST = 'REQUEST_GMC_LIST',
  REQUEST_DATA_SOURCE_LIST = 'REQUEST_DATA_SOURCE_LIST',
  CREATE_DATA_SOURCE = 'CREATE_DATA_SOURCE',
  DISSOCIATE_GOOGLE_ACCOUNT = 'DISSOCIATE_GOOGLE_ACCOUNT',
}

export {ActionsTypes as default};
