enum GetterTypes {
    /* Google Account */
    GET_GOOGLE_ACCOUNT_IS_ONBOARDED = 'GET_GOOGLE_ACCOUNT_IS_ONBOARDED',
    GET_GOOGLE_ACCOUNT = 'GET_GOOGLE_ACCOUNT',
    GET_GOOGLE_ACCOUNT_MCA_LIST = 'GET_GOOGLE_ACCOUNT_MCA_LIST',
    GET_GOOGLE_ACCOUNT_CONNECTED_ONCE = 'GET_GOOGLE_ACCOUNT_CONNECTED_ONCE',
    /* Merchant Center Account */
    GET_GOOGLE_MERCHANT_CENTER_ACCOUNT = 'GET_GOOGLE_MERCHANT_CENTER_ACCOUNT',
    GET_GOOGLE_MERCHANT_CENTER_ACCOUNT_IS_CONFIGURED= 'GET_GOOGLE_MERCHANT_CENTER_ACCOUNT_IS_CONFIGURED',
    GET_GOOGLE_ACCOUNT_AUTHENTICATION_URL = 'GET_GOOGLE_ACCOUNT_AUTHENTICATION_URL',
    GET_GOOGLE_ACCOUNT_WEBSITE_CLAIMING_ERROR_REASON = 'GET_GOOGLE_ACCOUNT_WEBSITE_CLAIMING_ERROR_REASON',
    GET_GOOGLE_ACCOUNT_WEBSITE_CLAIMING_OVERRIDE_STATUS = 'GET_GOOGLE_ACCOUNT_WEBSITE_CLAIMING_OVERRIDE_STATUS',
    GET_GOOGLE_MERCHANT_CENTER_ACCOUNT_CONNECTED_ONCE = 'GET_GOOGLE_MERCHANT_CENTER_ACCOUNT_CONNECTED_ONCE',
    GET_GOOGLE_MERCHANT_CENTER_IS_CONNECTED = 'GET_GOOGLE_MERCHANT_CENTER_IS_CONNECTED',
    GET_WEBSITE_REQUIREMENTS = 'GET_WEBSITE_REQUIREMENTS',
    GET_SHOP_INFORMATIONS = 'GET_SHOP_INFORMATIONS',
}

export {GetterTypes as default};
