enum GetterTypes {
  GET_GOOGLE_ACCOUNT_IS_ONBOARDED = 'GET_GOOGLE_ACCOUNT_IS_ONBOARDED',
  GET_GOOGLE_ACCOUNT = 'GET_GOOGLE_ACCOUNT',
  GET_GOOGLE_ACCOUNT_MCA_LIST = 'GET_GOOGLE_ACCOUNT_MCA_LIST',
  GET_GOOGLE_ACCOUNT_CONNECTED_ONCE = 'GET_GOOGLE_ACCOUNT_CONNECTED_ONCE',
  GET_LOCAL_GOOGLE_IS_CONFIGURED = 'GET_LOCAL_GOOGLE_IS_CONFIGURED',
  GET_LOCAL_GOOGLE_IS_READY = 'GET_LOCAL_GOOGLE_IS_READY',
  GET_GOOGLE_MERCHANT_CENTER_ACCOUNT = 'GET_GOOGLE_MERCHANT_CENTER_ACCOUNT',
  GET_GOOGLE_MERCHANT_CENTER_ACCOUNT_IS_CONFIGURED = 'GET_GOOGLE_MERCHANT_CENTER_ACCOUNT_IS_CONFIGURED',
  GET_GOOGLE_ACCOUNT_AUTHENTICATION_URL = 'GET_GOOGLE_ACCOUNT_AUTHENTICATION_URL',
  GET_GOOGLE_MERCHANT_CENTER_ACCOUNT_CONNECTED_ONCE = 'GET_GOOGLE_MERCHANT_CENTER_ACCOUNT_CONNECTED_ONCE',
  GET_GOOGLE_MERCHANT_CENTER_IS_CONNECTED = 'GET_GOOGLE_MERCHANT_CENTER_IS_CONNECTED',
  GET_MERCHANT_SELECTION_ERROR = 'GET_MERCHANT_SELECTION_ERROR',
}

export {GetterTypes as default};
