enum MutationsTypes {
  SET_GOOGLE_ACCOUNT = 'SET_GOOGLE_ACCOUNT',
  REMOVE_GOOGLE_ACCOUNT = 'REMOVE_GOOGLE_ACCOUNT',
  SAVE_GOOGLE_ACCOUNT_CONNECTED_ONCE = 'SAVE_GOOGLE_ACCOUNT_CONNECTED_ONCE',
  SAVE_GMC_LIST = 'SAVE_GMC_LIST',
  SAVE_GMC = 'SAVE_GMC',
  SAVE_DATA_SOURCE_LIST = 'SAVE_DATA_SOURCE_LIST',
  SAVE_DATA_SOURCE = 'SAVE_DATA_SOURCE',
  REMOVE_GMC = 'REMOVE_GMC',
  SAVE_MCA_CONNECTED_ONCE = 'SAVE_MCA_CONNECTED_ONCE',
  SET_GOOGLE_AUTHENTICATION_URL = 'SET_GOOGLE_AUTHENTICATION_URL',
  SET_MERCHANT_SELECTION_ERROR = 'SET_MERCHANT_SELECTION_ERROR',
}

export {MutationsTypes as default};
