preserve_hierarchy: true
files:
  - source: /_dev/src/assets/json/translations/en/ui.json
    translation: /_dev/src/assets/json/translations/%two_letters_code%/%original_file_name%
    skip_untranslated_strings: true
