enum GetterTypes {
  GET_IS_COUNTRY_MEMBER_OF_EU = 'GET_IS_COUNTRY_MEMBER_OF_EU',
  GET_CURRENT_CURRENCY = 'GET_CURRENT_CURRENCY',
  GET_DOC_AND_FAQ = 'GET_DOC_AND_FAQ',
  GET_STATUS_SHOP_MAINTENANCE = 'GET_STATUS_SHOP_MAINTENANCE',
  GET_PRODUCT_DETAIL_BASE_URL = 'GET_PRODUCT_DETAIL_BASE_URL',
  GET_STORE_INFORMATION_URL = 'GET_STORE_INFORMATION_URL',
  GET_ACTIVE_COUNTRIES = 'GET_ACTIVE_COUNTRIES',
}

export {GetterTypes as default};
