enum DailyResultType {
  IMPRESSIONS = 'IMPRESSIONS',
  CLICKS = 'CLICKS',
  CONVERSIONS = 'CONVERSIONS',
  AVERAGE_COST_CLICK = 'AVERAGE_COST_CLICK',
  COSTS = 'COSTS',
  SALES = 'SALES',
}

export default DailyResultType;
