enum GetterTypes {
    GET_PS_ACCOUNTS_IS_ONBOARDED = 'GET_PS_ACCOUNTS_IS_ONBOARDED',
    GET_PS_ACCOUNTS_CONTEXT = 'GET_PS_ACCOUNTS_CONTEXT',
    GET_PS_ACCOUNTS_CONTEXT_SHOPS = 'GET_PS_ACCOUNTS_CONTEXT_SHOPS',
}

export {GetterTypes as default};
