enum GetterTypes {
  GET_PRODUCT_FEED_IS_CONFIGURED = 'GET_PRODUCT_FEED_IS_CONFIGURED',
  GET_PRODUCT_FEED_IS_CONFIGURED_ONCE = 'GET_PRODUCT_FEED_IS_CONFIGURED_ONCE',
  GET_PRODUCT_FEED_SETTINGS = 'GET_PRODUCT_FEED_SETTINGS',
  GET_PRODUCT_FEED_STATUS = 'GET_PRODUCT_FEED_STATUS',
  GET_MERCHANT_SELL_APPAREL_AND_ACCESSORIES = 'GET_MERCHANT_SELL_APPAREL_AND_ACCESSORIES',
  GET_MERCHANT_SELL_REFURBISHED_PRODUCTS = 'GET_MERCHANT_SELL_REFURBISHED_PRODUCTS',
  GET_PRODUCT_FEED_VALIDATION_SUMMARY = 'GET_PRODUCT_FEED_VALIDATION_SUMMARY',
  GET_TOTAL_PRODUCTS = 'GET_TOTAL_PRODUCTS',
  GET_SYNC_STATUS = 'GET_SYNC_STATUS',
  GET_FREE_LISTING_ATTRIBUTES_TO_MAP = 'GET_FREE_LISTING_ATTRIBUTES_TO_MAP',
  GET_SHOP_ATTRIBUTES = 'GET_SHOP_ATTRIBUTES',
  GET_CATEGORIES_SELECTED = 'GET_CATEGORIES_SELECTED',
  GET_TARGET_COUNTRIES = 'GET_TARGET_COUNTRIES',
  GET_PRODUCT_CATEGORIES_SELECTED = 'GET_PRODUCT_CATEGORIES_SELECTED',
  GET_SYNC_SCHEDULE = 'GET_SYNC_SCHEDULE',
}

export {GetterTypes as default};
