enum GetterTypes {
  GET_PRODUCT_FEED_IS_CONFIGURED = 'GET_PRODUCT_FEED_IS_CONFIGURED',
  GET_PRODUCT_FEED_IS_CONFIGURED_ONCE = 'GET_PRODUCT_FEED_IS_CONFIGURED_ONCE',
  GET_PRODUCT_FEED_SETTINGS = 'GET_PRODUCT_FEED_SETTINGS',
  GET_PRODUCT_FEED_STATUS = 'GET_PRODUCT_FEED_STATUS',
  GET_MERCHANT_SELL_APPAREL_AND_ACCESSORIES = 'GET_MERCHANT_SELL_APPAREL_AND_ACCESSORIES',
  GET_MERCHANT_SELL_REFURBISHED_PRODUCTS = 'GET_MERCHANT_SELL_REFURBISHED_PRODUCTS',
  GET_ACTIVE_COUNTRY = 'GET_ACTIVE_COUNTRY',
  GET_PRODUCT_FEED_VALIDATION_SUMMARY = 'GET_PRODUCT_FEED_VALIDATION_SUMMARY',
  GET_TOTAL_PRODUCTS = 'GET_TOTAL_PRODUCTS',
  GET_SYNC_STATUS = 'GET_SYNC_STATUS',
}

export {GetterTypes as default};
