enum GetterTypes {
  GET_PRODUCT_FEED_IS_CONFIGURED = 'GET_PRODUCT_FEED_IS_CONFIGURED',
  GET_PRODUCT_FEED_SETTINGS = 'GET_PRODUCT_FEED_SETTINGS',
  GET_PRODUCT_FEED_STATUS = 'GET_PRODUCT_FEED_STATUS',
  GET_MERCHANT_SELL_APPAREL_AND_ACCESSORIES = 'GET_MERCHANT_SELL_APPAREL_AND_ACCESSORIES',
  GET_MERCHANT_SELL_REFURBISHED_PRODUCTS = 'GET_MERCHANT_SELL_REFURBISHED_PRODUCTS',
}

export {GetterTypes as default};
