enum GetterTypes {
  GET_IS_COUNTRY_MEMBER_OF_EU = 'GET_IS_COUNTRY_MEMBER_OF_EU',
  GET_CURRENT_LANGUAGE = 'GET_CURRENT_LANGUAGE',
  GET_CURRENT_CURRENCY = 'GET_CURRENT_CURRENCY',
  GET_SHOP_CURRENCIES = 'GET_SHOP_CURRENCIES',
  GET_DOC_AND_FAQ = 'GET_DOC_AND_FAQ',
  GET_SUPPORT_URL = 'GET_SUPPORT_URL',
  GET_DEBUG_DATA = 'GET_DEBUG_DATA',
  GET_STATUS_SHOP_MAINTENANCE = 'GET_STATUS_SHOP_MAINTENANCE',
  GET_CARRIERS_URL = 'GET_CARRIERS_URL',
  GET_ATTRIBUTES_URL = 'GET_ATTRIBUTES_URL',
  GET_PRODUCT_DETAIL_BASE_URL = 'GET_PRODUCT_DETAIL_BASE_URL',
  GET_PRODUCTS_CATALOG_URL = 'GET_PRODUCTS_CATALOG_URL',
  GET_CURRENCIES_URL = 'GET_CURRENCIES_URL',
  GET_LANGUAGES_URL = 'GET_LANGUAGES_URL',
  GET_STORE_INFORMATION_URL = 'GET_STORE_INFORMATION_URL',
  GET_ACTIVE_COUNTRIES = 'GET_ACTIVE_COUNTRIES',
  GET_ACTIVE_COUNTRIES_FOR_ACTIVE_CURRENCY = 'GET_ACTIVE_COUNTRIES_FOR_ACTIVE_CURRENCY',
  GET_ADD_BLOCKER_STATUS = 'GET_ADD_BLOCKER_STATUS',
  GET_SYMBOL_OF_CURRENT_CURRENCY = 'GET_SYMBOL_OF_CURRENT_CURRENCY',

  GET_FEATURE_FLAG_ENHANCED_CONVERSIONS = 'GET_FEATURE_FLAG_ENHANCED_CONVERSIONS',

  // Subscription
  GET_BILLING_SUBSCRIPTION_ACTIVE = 'GET_BILLING_SUBSCRIPTION_ACTIVE',
  GET_BILLING_SUBSCRIPTION_EXPIRING = 'GET_BILLING_SUBSCRIPTION_EXPIRING',
}

export {GetterTypes as default};
