enum GetterTypes {
  GET_GOOGLE_ADS_STATUS = 'GET_GOOGLE_ADS_STATUS',
  GET_GOOGLE_ADS_LIST_OPTIONS = 'GET_GOOGLE_ADS_LIST_OPTIONS',
  GET_GOOGLE_ADS_ACCOUNT_CHOSEN = 'GET_GOOGLE_ADS_ACCOUNT_CHOSEN',
  GET_GOOGLE_ADS_ACCOUNT_IS_SERVING = 'GET_GOOGLE_ADS_ACCOUNT_IS_SERVING',
  GET_GOOGLE_ADS_ACCOUNT_CONNECTED_ONCE = 'GET_GOOGLE_ADS_ACCOUNT_CONNECTED_ONCE',
  GET_BILLING_SHOP_INFORMATIONS = 'GET_BILLING_SHOP_INFORMATIONS',

  GET_CONVERSIONS_TERMS_OF_SERVICES_SIGNED = 'GET_CONVERSIONS_TERMS_OF_SERVICES_SIGNED'
}

export {GetterTypes as default};
