enum GetterTypes {
  GET_FREE_LISTING_STATUS = 'GET_FREE_LISTING_STATUS',
  GET_FREE_LISTING_STATUS_API = 'GET_FREE_LISTING_STATUS_API',
  GET_FREE_LISTING_IS_ACTIVATED_ONCE = 'GET_FREE_LISTING_IS_ACTIVATED_ONCE'
}

export default GetterTypes;
