name: CDN Publish Preproduction

on:
  push:
    branches:
      - master

env:
  WORKFLOW: googleshopping-storage.yml
  NODE_VERSION: 14
  VUE_PATH: _dev
  BUILD_PATH: views

jobs:
  publish:
    name: CDN publish
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: get_tag
        run: |
          echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)
          echo ::set-output name=MAJOR::$(echo $GITHUB_REF | cut -d / -f 3 | cut -d '.' -f 1)
          echo ::set-output name=MINOR::$(echo $GITHUB_REF | cut -d / -f 3 | cut -d '.' -f 2)
          echo ::set-output name=PATCH::$(echo $GITHUB_REF | cut -d / -f 3 | cut -d '.' -f 3)

      - name: Get assets URL
        id: get_assets_url
        run: |
          echo ::set-output name=URL::https://storage.googleapis.com/psxmarketing-preproduction-cdn/latest/
        env:
          MAJOR: ${{ steps.get_tag.outputs.MAJOR }}
          MINOR: ${{ steps.get_tag.outputs.MINOR }}
          PATCH: ${{ steps.get_tag.outputs.PATCH }}

      - name: Trigger storage preproduction
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: ${{ env.WORKFLOW }}
          repo: Quetzacoalt91/services-deployment
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: 'refs/heads/introduce-pnpm-for-google'
          inputs: '{ "version": "${{ steps.get_tag.outputs.TAG }}", "nodeVersion": "${{ env.NODE_VERSION }}", "pnpmVersion": "${{ env.PNPM_VERSION }}", "vuejsPath": "${{ env.VUE_PATH }}", "vuejsBuildPath": "${{ env.BUILD_PATH }}", "isRelease": "false", "environment": "preproduction", "assetsUrl": "${{ steps.get_assets_url.outputs.URL }}" }'

